using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.UI;
using Windows.UI.Xaml.Media;

namespace P42.Utils.Uno
{
    // Full list of system brushes found here: https://github.com/MicrosoftDocs/windows-uwp/issues/2072
    public static class SystemCheckBoxBrushes
    {
        public static Brush Background => ColorExtensions.AppBrush("CheckBoxBackgroundThemeBrush");
        public static Brush Border => ColorExtensions.AppBrush("CheckBoxBorderThemeBrush");
        public static Brush ContentDisabledForeground => ColorExtensions.AppBrush("CheckBoxContentDisabledForegroundThemeBrush");
        public static Brush ContentForeground => ColorExtensions.AppBrush("CheckBoxContentForegroundThemeBrush");
        public static Brush DisabledBackground => ColorExtensions.AppBrush("CheckBoxDisabledBackgroundThemeBrush");
        public static Brush DisabledBorder => ColorExtensions.AppBrush("CheckBoxDisabledBorderThemeBrush");
        public static Brush DisabledForeground => ColorExtensions.AppBrush("CheckBoxDisabledForegroundThemeBrush");
        public static Brush Foreground => ColorExtensions.AppBrush("CheckBoxForegroundThemeBrush");
        public static Brush PointerOverBackground => ColorExtensions.AppBrush("CheckBoxPointerOverBackgroundThemeBrush");
        public static Brush PointerOverBorder => ColorExtensions.AppBrush("CheckBoxPointerOverBorderThemeBrush");
        public static Brush PointerOverForeground => ColorExtensions.AppBrush("CheckBoxPointerOverForegroundThemeBrush");
        public static Brush PressedBackground => ColorExtensions.AppBrush("CheckBoxPressedBackgroundThemeBrush");
        public static Brush PressedBorder => ColorExtensions.AppBrush("CheckBoxPressedBorderThemeBrush");
        public static Brush PressedForeground => ColorExtensions.AppBrush("CheckBoxPressedForegroundThemeBrush");

        public static Brush ForegroundUnchecked => ColorExtensions.AppBrush("CheckBoxForegroundUnchecked");
        public static Brush ForegroundUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxForegroundUncheckedPointerOver");
        public static Brush ForegroundUncheckedPressed => ColorExtensions.AppBrush("CheckBoxForegroundUncheckedPressed");
        public static Brush ForegroundUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxForegroundUncheckedDisabled");
        public static Brush ForegroundChecked => ColorExtensions.AppBrush("CheckBoxForegroundChecked");
        public static Brush ForegroundCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxForegroundCheckedPointerOver");
        public static Brush ForegroundCheckedPressed => ColorExtensions.AppBrush("CheckBoxForegroundCheckedPressed");
        public static Brush ForegroundCheckedDisabled => ColorExtensions.AppBrush("CheckBoxForegroundCheckedDisabled");
        public static Brush ForegroundIndeterminate => ColorExtensions.AppBrush("CheckBoxForegroundIndeterminate");
        public static Brush ForegroundIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxForegroundIndeterminatePointerOver");
        public static Brush ForegroundIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxForegroundIndeterminatePressed");
        public static Brush ForegroundIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxForegroundIndeterminateDisabled");
        public static Brush BackgroundUnchecked => ColorExtensions.AppBrush("CheckBoxBackgroundUnchecked");
        public static Brush BackgroundUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxBackgroundUncheckedPointerOver");
        public static Brush BackgroundUncheckedPressed => ColorExtensions.AppBrush("CheckBoxBackgroundUncheckedPressed");
        public static Brush BackgroundUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxBackgroundUncheckedDisabled");
        public static Brush BackgroundChecked => ColorExtensions.AppBrush("CheckBoxBackgroundChecked");
        public static Brush BackgroundCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxBackgroundCheckedPointerOver");
        public static Brush BackgroundCheckedPressed => ColorExtensions.AppBrush("CheckBoxBackgroundCheckedPressed");
        public static Brush BackgroundCheckedDisabled => ColorExtensions.AppBrush("CheckBoxBackgroundCheckedDisabled");
        public static Brush BackgroundIndeterminate => ColorExtensions.AppBrush("CheckBoxBackgroundIndeterminate");
        public static Brush BackgroundIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxBackgroundIndeterminatePointerOver");
        public static Brush BackgroundIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxBackgroundIndeterminatePressed");
        public static Brush BackgroundIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxBackgroundIndeterminateDisabled");
        public static Brush BorderBrushUnchecked => ColorExtensions.AppBrush("CheckBoxBorderBrushUnchecked");
        public static Brush BorderBrushUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxBorderBrushUncheckedPointerOver");
        public static Brush BorderBrushUncheckedPressed => ColorExtensions.AppBrush("CheckBoxBorderBrushUncheckedPressed");
        public static Brush BorderBrushUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxBorderBrushUncheckedDisabled");
        public static Brush BorderBrushChecked => ColorExtensions.AppBrush("CheckBoxBorderBrushChecked");
        public static Brush BorderBrushCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxBorderBrushCheckedPointerOver");
        public static Brush BorderBrushCheckedPressed => ColorExtensions.AppBrush("CheckBoxBorderBrushCheckedPressed");
        public static Brush BorderBrushCheckedDisabled => ColorExtensions.AppBrush("CheckBoxBorderBrushCheckedDisabled");
        public static Brush BorderBrushIndeterminate => ColorExtensions.AppBrush("CheckBoxBorderBrushIndeterminate");
        public static Brush BorderBrushIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxBorderBrushIndeterminatePointerOver");
        public static Brush BorderBrushIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxBorderBrushIndeterminatePressed");
        public static Brush BorderBrushIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxBorderBrushIndeterminateDisabled");
        public static Brush CheckBackgroundStrokeUnchecked => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeUnchecked");
        public static Brush CheckBackgroundStrokeUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeUncheckedPointerOver");
        public static Brush CheckBackgroundStrokeUncheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeUncheckedPressed");
        public static Brush CheckBackgroundStrokeUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeUncheckedDisabled");
        public static Brush CheckBackgroundStrokeChecked => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeChecked");
        public static Brush CheckBackgroundStrokeCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeCheckedPointerOver");
        public static Brush CheckBackgroundStrokeCheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeCheckedPressed");
        public static Brush CheckBackgroundStrokeCheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeCheckedDisabled");
        public static Brush CheckBackgroundStrokeIndeterminate => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeIndeterminate");
        public static Brush CheckBackgroundStrokeIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeIndeterminatePointerOver");
        public static Brush CheckBackgroundStrokeIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeIndeterminatePressed");
        public static Brush CheckBackgroundStrokeIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundStrokeIndeterminateDisabled");
        public static Brush CheckBackgroundFillUnchecked => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillUnchecked");
        public static Brush CheckBackgroundFillUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillUncheckedPointerOver");
        public static Brush CheckBackgroundFillUncheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillUncheckedPressed");
        public static Brush CheckBackgroundFillUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillUncheckedDisabled");
        public static Brush CheckBackgroundFillChecked => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillChecked");
        public static Brush CheckBackgroundFillCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillCheckedPointerOver");
        public static Brush CheckBackgroundFillCheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillCheckedPressed");
        public static Brush CheckBackgroundFillCheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillCheckedDisabled");
        public static Brush CheckBackgroundFillIndeterminate => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillIndeterminate");
        public static Brush CheckBackgroundFillIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillIndeterminatePointerOver");
        public static Brush CheckBackgroundFillIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillIndeterminatePressed");
        public static Brush CheckBackgroundFillIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxCheckBackgroundFillIndeterminateDisabled");
        public static Brush CheckGlyphForegroundUnchecked => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundUnchecked");
        public static Brush CheckGlyphForegroundUncheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundUncheckedPointerOver");
        public static Brush CheckGlyphForegroundUncheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundUncheckedPressed");
        public static Brush CheckGlyphForegroundUncheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundUncheckedDisabled");
        public static Brush CheckGlyphForegroundChecked => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundChecked");
        public static Brush CheckGlyphForegroundCheckedPointerOver => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundCheckedPointerOver");
        public static Brush CheckGlyphForegroundCheckedPressed => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundCheckedPressed");
        public static Brush CheckGlyphForegroundCheckedDisabled => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundCheckedDisabled");
        public static Brush CheckGlyphForegroundIndeterminate => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundIndeterminate");
        public static Brush CheckGlyphForegroundIndeterminatePointerOver => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundIndeterminatePointerOver");
        public static Brush CheckGlyphForegroundIndeterminatePressed => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundIndeterminatePressed");
        public static Brush CheckGlyphForegroundIndeterminateDisabled => ColorExtensions.AppBrush("CheckBoxCheckGlyphForegroundIndeterminateDisabled");
    }
}
