<Project ToolsVersion="15.0">


  <!-- SHARED ITEMS -->
  <ItemGroup>
    <PackageReference Include="Markdig.Signed"  />
    <PackageReference Include="HtmlAgilityPack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\P42.Utils.Uno\P42.Utils.Uno.csproj" />
  </ItemGroup>

</Project>
